version: '3'

services:
  php:
    build: ./docker/php
    volumes:
      - ./learn:/var/www/html:cached
    depends_on: [mysql]
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8083:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      - ./learn:/var/www/html
    networks:
      - app-network
    depends_on: [php]

  mysql:
    image: mysql:latest
    container_name: mysql_to_play
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: to_play
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3316:3306"
    volumes:
      - mysql_data:/var/utils/mysql

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: